<?php
return array(
    'priority' => 1,
    'items' => array(
        '([\w-_]+)-ncat(\d+)\/(\d+)-(\d+)-(\d+)\.html' => array(
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname}-ncat{catId}/{date}-{month}-{year}.html'),
        '([\w-_]+)\/([\w-_]+)\/([\w-_]+)\/(\d+)\/([\w-_]+)\.html' => array(
                                'module' =>'News',
                                'controller' => 'NewsComponent',
                                'action' => 'detailNews',
                                'url' => '{catname1}/{catname2}/{catname3}/{nid}/{name}.html'),
        '([\w-_]+)\/([\w-_]+)\/(\d+)\/([\w-_]+)\.html' => array(
                                'module' =>'News',
                                'controller' => 'NewsComponent',
                                'action' => 'detailNews',
                                'url' => '{catname1}/{catname2}/{nid}/{name}.html'),
        '([\w-_]+)\/([\w-_]+)-(\d+)\.html' => array(
                                'module' =>'News',
                                'controller' => 'NewsComponent',
                                'action' => 'detailNews',
                                'url' => '{catname1}/{name}-{nid}.html'),
        '([\w-_]+)-(\d+)\.html' => array(
                                'module' =>'News',
                                'controller' => 'NewsComponent',
                                'action' => 'detailNews',
                                'url' => '{name}-{nid}.html'),

        '([\w-_]+)\/([\w-_]+)\/([\w-_]+)-ncat(\d+)\/trang-(\d+)' => array(
                                'langcode' => 'vi-VN',
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname1}/{catname2}/{catname3}-ncat{catId}/trang-{page}'),
        '([\w-_]+)\/([\w-_]+)\/([\w-_]+)-ncat(\d+)\/page-(\d+)' => array(
                                'langcode' => 'en-US',
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname1}/{catname2}/{catname3}-ncat{catId}/page-{page}'),
        '([\w-_]+)\/([\w-_]+)-ncat(\d+)\/trang-(\d+)' => array(
                                'langcode' => 'vi-VN',
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname1}/{catname2}-ncat{catId}/trang-{page}'),
        '([\w-_]+)\/([\w-_]+)-ncat(\d+)\/page-(\d+)\.html' => array(
                                'langcode' => 'en-US',
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname1}/{catname2}-ncat{catId}/page-{page}'),
        '([\w-_]+)-ncat(\d+)\/trang-(\d+)' => array(
                                'langcode' => 'vi-VN',
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname}-ncat{catId}/trang-{page}'),
        '([\w-_]+)-ncat(\d+)\/page-(\d+)' => array(
                                'langcode' => 'en-US',
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname}-ncat{catId}/page-{page}'),
        '([\w-_]+)\/([\w-_]+)-ncat(\d+)' => array(
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catname}/{catname2}-ncat{catId}'),
        '([\w-_]+)-ncat(\d+)' => array(
                                'module' => 'News',
                                'controller' => 'NewsComponent',
                                'action' => 'listNewsCat',
                                'url' => '{catnameo}-ncat{catId}'))
);